### ISSUE TITLE
Error: ENOENT, No such file or directory

### ISSUE THREAD

**Issue by kyxxer** [HashLips/generative-art-node#82]
/

**Comment by DarkSIdePan** [comment]
Hey @kyxxer how did you fix this? Im getting the same error

**Comment by gurselcesur** [comment]
i have same error too

**Comment by goawarness** [comment]
> Hey @kyxxer how did you fix this? Im getting the same error



> i have same error too

The reason for the problem is that there is a file that does not contain English characters in the path of the hashlpis art engine file. So your hashlips file may be in a path like C:/users/username/onedrive/deskştop (or desksğtop, or deskçtop)/hashlips_art_engine. Make sure your file is in a path that contains only English characters. This is the definitive solution to this problem.
